using System;

namespace RTDP
{
    public class DXKeyboardSimulator
    {
        private bool[] pressed;

        public DXKeyboardSimulator()
        {
            pressed = new bool[0xFF];
        }

        public void SendKey(int key, Petition petition)
        {
            try
            {
                DirectXKeyStrokes keycode = (DirectXKeyStrokes)Enum.Parse(typeof(DirectXKeyStrokes), ((Key)key).ToString());
                Console.WriteLine((petition == Petition.KeyboardKeyDown? "Pressed: " : "Released: ") + keycode.ToString());

                if (pressed[(int)DirectXKeyStrokes.LeftCtrl] && pressed[(int)DirectXKeyStrokes.RightAlt] && (Key)key == Key.System)
                    keycode = DirectXKeyStrokes.LeftCtrl;

                pressed[(int)keycode] = petition == Petition.KeyboardKeyDown;

                NativeMethods.SendInput(new Input[]
                {
                new Input
                {
                    type = (int) InputType.Keyboard,
                    u = new InputUnion
                    {
                        ki = new KeyboardInput
                        {
                            wVk = 0,
                            wScan = (ushort) keycode,
                            dwFlags = (uint) ((petition == Petition.KeyboardKeyUp ? KeyEventF.KeyUp : KeyEventF.KeyDown) | KeyEventF.Scancode | KeyEventF.Unicode),
                            dwExtraInfo = NativeMethods.GetMessageExtraInfo()
                        }
                    }
                }
                });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

        public void ReleaseAllKeys()
        {
            foreach(int key in Enum.GetValues(typeof(DirectXKeyStrokes)))
                if (pressed[key])
                    SendKey(key, Petition.KeyboardKeyUp);
        }
    }

    enum DirectXKeyStrokes
    {
        Escape = 0x01,
        D1 = 0x02,
        D2 = 0x03,
        D3 = 0x04,
        D4 = 0x05,
        D5 = 0x06,
        D6 = 0x07,
        D7 = 0x08,
        D8 = 0x09,
        D9 = 0x0A,
        D0 = 0x0B,
        OemOpenBrackets = 0x0C,         Oem6 = 0x0D,         Back = 0x0E,

        Tab = 0x0F,
        Q = 0x10,
        W = 0x11,
        E = 0x12,
        R = 0x13,
        T = 0x14,
        Y = 0x15,
        U = 0x16,
        I = 0x17,
        O = 0x18,
        P = 0x19,
        Oem1 = 0x1A,                OemPlus = 0x1B,
        Return = 0x1C,

        LeftCtrl = 0x1D,
        A = 0x1E,
        S = 0x1F,
        D = 0x20,
        F = 0x21,
        G = 0x22,
        H = 0x23,
        J = 0x24,
        K = 0x25,
        L = 0x26,
        Oem3 = 0x27,                OemQuotes = 0x28,           Oem5 = 0x29,        
        LeftShift = 0x2A,
        OemQuestion = 0x2B,         Z = 0x2C,
        X = 0x2D,
        C = 0x2E,
        V = 0x2F,
        B = 0x30,
        N = 0x31,
        M = 0x32,
        OemComma = 0x33,
        OemPeriod = 0x34,
        OemMinus = 0x35,
        RightShift = 0x36,

        Multiply = 0x37,
        LeftAlt = 0x38,
        Space = 0x39,
        Capital = 0x3A,

        F1 = 0x3B,
        F2 = 0x3C,
        F3 = 0x3D,
        F4 = 0x3E,
        F5 = 0x3F,
        F6 = 0x40,
        F7 = 0x41,
        F8 = 0x42,
        F9 = 0x43,
        F10 = 0x44,
        NumLock = 0x45,
        Scroll = 0x46,

        NumPad7 = 0x47,
        NumPad8 = 0x48,
        NumPad9 = 0x49,
        Subtract = 0x4A,

        NumPad4 = 0x4B,
        NumPad5 = 0x4C,
        NumPad6 = 0x4D,
        Add = 0x4E,

        NumPad1 = 0x4F,
        NumPad2 = 0x50,
        NumPad3 = 0x51,
        NumPad0 = 0x52,
        Decimal = 0x53,

        Snapshot = 0x54,

        OemBackslash = 0x56,                F11 = 0x57,
        F12 = 0x58,

        Clear = 0x59,               
        F13 = 0x64,
        F14 = 0x65,
        F15 = 0x66,

        KanaMode = 0x70,
        AbntC1 = 0x73,
        DIK_CONVERT = 0x79,
        DIK_NOCONVERT = 0x7B,
        OemBackTab = 0x7C,
        DIK_YEN = 0x7D,
        AbntC2 = 0x7E,

        /** Extended Keys **/
        DIK_NUMPADEQUALS = 0x8D,            MediaPreviousTrack = 0x90,
        DIK_AT = 0x91,                      DIK_COLON = 0x92,                   DIK_UNDERLINE = 0x93,               KanjiMode = 0x94,                   DIK_STOP = 0x95,                    DIK_AX = 0x96,                      DIK_UNLABELED = 0x97,               MediaNextTrack = 0x99,
        DIK_NUMPADENTER = 0x9C,             RightCtrl = 0x9D,
        VolumeMute = 0xA0,
        DIK_CALCULATOR = 0xA1,              MediaPlayPause = 0xA2,
        MediaStop = 0xA4,
        VolumeDown = 0xAE,
        VolumeUp = 0xB0,
        BrowserHome = 0xB2,
        DIK_NUMPADCOMMA = 0xB3,     
        Divide = 0xB5,
        DIK_SYSRQ = 0xB7,
        RightAlt = 0xB8,
        Pause = 0xC5,
        Home = 0xC7,
        Up = 0xC8,
        Prior = 0xC9,
        Left = 0xCB,
        Right = 0xCD,
        End = 0xCF,
        Down = 0xD0,
        Next = 0xD1,
        Insert = 0xD2,
        Delete = 0xD3,
        LWin = 0xDB,
        RWin = 0xDC,

        Apps = 0xDD,
        DIK_POWER = 0xDE,                   Sleep = 0xDF,
        DIK_WAKE = 0xE3,                    BrowserSearch = 0xE5,
        BrowserFavorites = 0xE6,
        BrowserRefresh = 0xE7,
        BrowserStop = 0xE8,
        BrowserForward = 0xE9,
        BrowserBack = 0xEA,
        DIK_MYCOMPUTER = 0xEB,              LaunchMail = 0xEC,
        SelectMedia = 0xED,

        PageUp = Prior,
        PageDown = Next,
        System = LeftAlt

        /** Mouse events?  
        DIK_LEFTMOUSEBUTTON = 0x100,
        DIK_RIGHTMOUSEBUTTON = 0x101,
        DIK_MIDDLEWHEELBUTTON = 0x102,
        DIK_MOUSEBUTTON3 = 0x103,
        DIK_MOUSEBUTTON4 = 0x104,
        DIK_MOUSEBUTTON5 = 0x105,
        DIK_MOUSEBUTTON6 = 0x106,
        DIK_MOUSEBUTTON7 = 0x107,
        DIK_MOUSEWHEELUP = 0x108,
        DIK_MOUSEWHEELDOWN = 0x109,
        **/
    }
    enum Key
    {
        None = 0,
        Cancel = 1,
        Back = 2,
        Tab = 3,
        LineFeed = 4,
        Clear = 5,
        Return = 6,
                                Enter = 6,
                                Pause = 7,
                                Capital = 8,
                                CapsLock = 8,
                                KanaMode = 9,
                                HangulMode = 9,
                                JunjaMode = 10,
                                FinalMode = 11,
                                HanjaMode = 12,
                                KanjiMode = 12,
                                Escape = 13,
                                ImeConvert = 14,
                                ImeNonConvert = 15,
                                ImeAccept = 16,
                                ImeModeChange = 17,
                                Space = 18,
                                Prior = 19,
                                PageUp = 19,
                                Next = 20,
                                PageDown = 20,
                                End = 21,
                                Home = 22,
                                Left = 23,
                                Up = 24,
                                Right = 25,
                                Down = 26,
                                Select = 27,
                                Print = 28,
                                Execute = 29,
                                Snapshot = 30,
                                PrintScreen = 30,
                                Insert = 31,
                                Delete = 32,
                                Help = 33,
                                D0 = 34,
                                D1 = 35,
                                D2 = 36,
                                D3 = 37,
                                D4 = 38,
                                D5 = 39,
                                D6 = 40,
                                D7 = 41,
                                D8 = 42,
                                D9 = 43,
                                A = 44,
                                B = 45,
                                C = 46,
                                D = 47,
                                E = 48,
                                F = 49,
                                G = 50,
                                H = 51,
                                I = 52,
                                J = 53,
                                K = 54,
                                L = 55,
                                M = 56,
                                N = 57,
                                O = 58,
                                P = 59,
                                Q = 60,
                                R = 61,
                                S = 62,
                                T = 63,
                                U = 64,
                                V = 65,
                                W = 66,
                                X = 67,
                                Y = 68,
                                Z = 69,
                                LWin = 70,
                                RWin = 71,
                                Apps = 72,
                                Sleep = 73,
                                NumPad0 = 74,
                                NumPad1 = 75,
                                NumPad2 = 76,
                                NumPad3 = 77,
                                NumPad4 = 78,
                                NumPad5 = 79,
                                NumPad6 = 80,
                                NumPad7 = 81,
                                NumPad8 = 82,
                                NumPad9 = 83,
                                Multiply = 84,
                                Add = 85,
                                Separator = 86,
                                Subtract = 87,
                                Decimal = 88,
                                Divide = 89,
                                F1 = 90,
                                F2 = 91,
                                F3 = 92,
                                F4 = 93,
                                F5 = 94,
                                F6 = 95,
                                F7 = 96,
                                F8 = 97,
                                F9 = 98,
                                F10 = 99,
                                F11 = 100,
                                F12 = 101,
                                F13 = 102,
                                F14 = 103,
                                F15 = 104,
                                F16 = 105,
                                F17 = 106,
                                F18 = 107,
                                F19 = 108,
                                F20 = 109,
                                F21 = 110,
                                F22 = 111,
                                F23 = 112,
                                F24 = 113,
                                NumLock = 114,
                                Scroll = 115,
                                LeftShift = 116,
                                RightShift = 117,
                                LeftCtrl = 118,
                                RightCtrl = 119,
                                LeftAlt = 120,
                                RightAlt = 121,
                                BrowserBack = 122,
                                BrowserForward = 123,
                                BrowserRefresh = 124,
                                BrowserStop = 125,
                                BrowserSearch = 126,
                                BrowserFavorites = 127,
                                BrowserHome = 128,
                                VolumeMute = 129,
                                VolumeDown = 130,
                                VolumeUp = 131,
                                MediaNextTrack = 132,
                                MediaPreviousTrack = 133,
                                MediaStop = 134,
                                MediaPlayPause = 135,
                                LaunchMail = 136,
                                SelectMedia = 137,
                                LaunchApplication1 = 138,
                                LaunchApplication2 = 139,
                                Oem1 = 140,
                                OemSemicolon = 140,
                                OemPlus = 141,
                                OemComma = 142,
                                OemMinus = 143,
                                OemPeriod = 144,
                                Oem2 = 145,
                                OemQuestion = 145,
                                Oem3 = 146,
                                OemTilde = 146,
                                AbntC1 = 147,
                                AbntC2 = 148,
                                Oem4 = 149,
                                OemOpenBrackets = 149,
                                Oem5 = 150,
                                OemPipe = 150,
                                Oem6 = 151,
                                OemCloseBrackets = 151,
                                Oem7 = 152,
                                OemQuotes = 152,
                                Oem8 = 153,
                                Oem102 = 154,
                                OemBackslash = 154,
                                ImeProcessed = 155,
                                        System = 156,
                                OemAttn = 157,
                                DbeAlphanumeric = 157,
                                OemFinish = 158,
                                DbeKatakana = 158,
                                OemCopy = 159,
                                DbeHiragana = 159,
                                OemAuto = 160,
                                DbeSbcsChar = 160,
                                OemEnlw = 161,
                                DbeDbcsChar = 161,
                                OemBackTab = 162,
                                DbeRoman = 162,
                                Attn = 163,
                                DbeNoRoman = 163,
                                CrSel = 164,
                                DbeEnterWordRegisterMode = 164,
                                ExSel = 165,
                                DbeEnterImeConfigureMode = 165,
                                EraseEof = 166,
                                DbeFlushString = 166,
                                Play = 167,
                                DbeCodeInput = 167,
                                Zoom = 168,
                                DbeNoCodeInput = 168,
                                NoName = 169,
                                DbeDetermineString = 169,
                                Pa1 = 170,
                                DbeEnterDialogConversionMode = 170,
                                OemClear = 171,
                                DeadCharProcessed = 172
    }
}
